### ISSUE TITLE
google translate connection error

### ISSUE THREAD

**Issue by silasness1** [dileivas/DAnki#1]
Hello, I'm learning German and I love your program! I was wondering if you could help me troubleshoot this error I'm getting. I've followed your instructions for the setup to the best of my ability. I mainly want to use DAnki to convert my own csv of German words/sentences to flashcards. It has no problems when it finds the vocabulary in Leo but the google translate feature doesn't seem to be working. Do you have any advice for me? I've copied what I got from my python terminal. (I don't think it's simply because "ajoke" isn't a German word. I've tried others. Danke in Voraus!

... (continues to translate words from leo successfully)...
Word: ausstellen | Word class: VVINF | Without Declination: ausstellen | Audio #: 7
Word: ajoke | Word class: NE | Without Declination: ajoke | Audio #: 8

Connection error for word ajoke: 404
Trying again for word ajoke
Connection error for word ajoke too: 404
Cant find such words as ajoke or ajoke in Leo!
Getting translation by Google Translator!

Traceback (most recent call last):

  File "C:\Users\Silas\Documents\AnkiProjects\theGeneratorScript.py", line 16, in <module>
    myDanki.create_translated_deck()

  File "C:\Users\Silas\anaconda3\lib\site-packages\DAnki\DAnki.py", line 389, in create_translated_deck
    self.create_main_table()

  File "C:\Users\Silas\anaconda3\lib\site-packages\DAnki\DAnki.py", line 275, in create_main_table
    self.search_leo_de(self.language, row, table_name, word, tag, lemma, word_class)

  File "C:\Users\Silas\anaconda3\lib\site-packages\DAnki\DAnki.py", line 232, in search_leo_de
    translation = self.traslate_with_google(lemma, lang) #colocar outros idiomas

  File "C:\Users\Silas\anaconda3\lib\site-packages\DAnki\DAnki.py", line 84, in traslate_with_google
    translation = Translator().translate(text, dest=lang_dest, src='de').text

  File "C:\Users\Silas\anaconda3\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)

  File "C:\Users\Silas\anaconda3\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)

  File "C:\Users\Silas\anaconda3\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()

  File "C:\Users\Silas\anaconda3\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dileivas** [comment]
Hey silasness1, how are you doing?

Actually I'm having this same problem here with Google Translation. I'm working on an update to fix this problem, maybe getting the translation from another source.

Thank you very much for your feedback and it's alredy amazing that you could provide by yourself the correct configuration to run this program (I know, that's not easy!).

I will be in touch when I get the program ready.

DAnki!

**Comment by silasness1** [comment]
Hey, I finally circled back to this problem and I've learned more programming since back then! I found the issue was actually on the google side. Just had to uninstall and reinstall google translate with a version above 3.0.0. 
Might be helpful to consider changing the setup.py to reflect that. The problem should fix for new people who download DAnki after google eventually updates the default version they install. Thanks again for this program it's wonderful!

https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group

**Comment by dileivas** [comment]
Hey silasness1, really thanks for your help here! I really appreciate it!
I was testing your solution today with googletrans upgrade, but unfortunately for me same problem remains: 

AttributeError: 'NoneType' object has no attribute 'group'

This solution is still working fine for you?

Thanks again!

**Comment by dileivas** [comment]
OMG, I just forgot to restart the kernel from Jupyter. 
Your solution worked fine! DAnki is alive again!

Thanks silasness1! You are the best!
